# Generated by Django 2.2.4 on 2019-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20191005_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='debt',
            field=models.IntegerField(null=True),
        ),
    ]
