# Generated by Django 2.2.4 on 2019-10-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20191009_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='amount',
            new_name='quantity',
        ),
    ]
