# Generated by Django 2.2.4 on 2019-10-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='aerning',
            field=models.IntegerField(null=True),
        ),
    ]
