# Generated by Django 2.2.4 on 2019-10-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_aerning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='aerning',
            new_name='earning',
        ),
    ]
