# Generated by Django 2.2.4 on 2019-10-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='items',
        ),
    ]
